# Generated by Django 5.2.7 on 2025-10-17 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Spaces allowed.', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
