# Generated by Django 5.2.7 on 2025-10-22 17:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccrualCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория начисления')),
            ],
            options={
                'verbose_name': 'Категория начисления',
                'verbose_name_plural': 'Категории начислений',
            },
        ),
        migrations.CreateModel(
            name='Etrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etrap', models.CharField(max_length=32, verbose_name='Etrap')),
                ('code', models.CharField(max_length=8, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Этрап',
                'verbose_name_plural': 'Этрапы',
            },
        ),
        migrations.CreateModel(
            name='UserDogowor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogowor', models.CharField(max_length=500, verbose_name='Договор')),
                ('balance_type', models.CharField(choices=[('telefon', 'Телефония'), ('internet', 'Интернет'), ('belet', 'Belet'), ('iptv', 'IPTV'), ('ctv', 'CTV')], max_length=50, verbose_name='Тип услуги')),
            ],
        ),
        migrations.CreateModel(
            name='UserActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('import_excel', 'Импорт из Excel'), ('export_excel', 'Экспорт в Excel'), ('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('other', 'Другое')], max_length=50, verbose_name='Тип действия')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Модель / объект')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание действия')),
                ('file', models.FileField(blank=True, null=True, upload_to='history_excel/', verbose_name='Файл Excel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История действий пользователя',
                'verbose_name_plural': 'История действий пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DogoworSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('dogowor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='core.userdogowor', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Сальдо',
                'verbose_name_plural': 'Сальдо',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DogoworPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма платежа')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='Способ оплаты (касса, банк, онлайн и т.д.)')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий / описание')),
                ('date', models.DateTimeField(verbose_name='Дата платежа')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Когда добавлено в систему')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogowor_payments', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('dogowor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.userdogowor', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DogoworBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('dogowor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='balance', to='core.userdogowor', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Балансы',
            },
        ),
        migrations.CreateModel(
            name='DogoworAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма начисления')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий / описание')),
                ('year', models.CharField(max_length=4, verbose_name='Год начисления')),
                ('month', models.CharField(max_length=2, verbose_name='Месяц начисления')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.accrualcategory', verbose_name='Категория')),
                ('dogowor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accruals', to='core.userdogowor', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, verbose_name='Номер телефона')),
                ('surname', models.CharField(blank=True, max_length=500, verbose_name='Фамилия/организация')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Имя/Отдел')),
                ('patronymic', models.CharField(blank=True, max_length=500, verbose_name='Отчество')),
                ('street', models.CharField(blank=True, max_length=500, verbose_name='Улица')),
                ('home', models.CharField(blank=True, max_length=64, verbose_name='Дом')),
                ('flat', models.CharField(blank=True, max_length=64, verbose_name='Квартира')),
                ('sotowyy', models.CharField(blank=True, max_length=32, verbose_name='Сотовый номер')),
                ('is_enterprises', models.BooleanField(blank=True, default=False, verbose_name='Предприятия')),
                ('account', models.IntegerField(blank=True, null=True, verbose_name='Счёт')),
                ('hb_type', models.CharField(blank=True, choices=[('hoz', 'Хозяйственный'), ('budjet', 'Бюджетный')], max_length=6, verbose_name='Хоз/Бюджет')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='Активный?')),
                ('etrap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.etrap')),
            ],
            options={
                'verbose_name': 'Абонент',
                'verbose_name_plural': 'Абоненты',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='userdogowor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dogowors', to='core.usertable', verbose_name='Абонент'),
        ),
        migrations.CreateModel(
            name='YearlyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('start_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сальдо на начало года')),
                ('end_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сальдо на конец года')),
                ('dogowor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yearly_balances', to='core.userdogowor', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Годовое сальдо',
                'verbose_name_plural': 'Годовые сальдо',
                'ordering': ['-year'],
            },
        ),
    ]
