# Generated by Django 5.2.7 on 2025-10-23 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etrap',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Активный?'),
        ),
        migrations.AlterField(
            model_name='dogoworaccrual',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.accrualcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='dogoworpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dogowor_payments', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='useractionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='YearlyBalance',
        ),
    ]
