# Generated by Django 5.2.7 on 2025-10-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_etrap_is_active_alter_dogoworaccrual_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etrap',
            options={'ordering': ['code'], 'verbose_name': 'Этрап', 'verbose_name_plural': 'Этрапы'},
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='home',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='street',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='surname',
        ),
        migrations.AddField(
            model_name='usertable',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ф.И.О/Отдел'),
        ),
    ]
