# Generated by Django 5.2.7 on 2025-10-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_etrap_options_remove_usertable_flat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdogowor',
            name='activate_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата Подключения'),
        ),
        migrations.AddField(
            model_name='userdogowor',
            name='deactivate_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата Отключения'),
        ),
        migrations.DeleteModel(
            name='DogoworSaldo',
        ),
    ]
