# Generated by Django 5.2.7 on 2025-10-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userdogowor_activate_at_userdogowor_deactivate_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='patronymic',
            field=models.CharField(blank=True, max_length=500, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='surname',
            field=models.CharField(blank=True, max_length=500, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Имя'),
        ),
    ]
