# Generated by Django 5.2.7 on 2025-10-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usertable_patronymic_usertable_surname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='sotowyy',
            new_name='mobile_number',
        ),
    ]
