# Generated by Django 5.2.7 on 2025-10-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_sotowyy_usertable_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdogowor',
            name='deactivate_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата Отключения'),
        ),
    ]
