# Generated by Django 5.2.7 on 2025-10-29 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userdogowor_deactivate_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdogowor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogowors', to='core.usertable', verbose_name='Абонент'),
        ),
    ]
