# Generated by Django 5.2.7 on 2025-10-29 16:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userdogowor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogoworbalance',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
    ]
