# Generated by Django 5.2.7 on 2025-10-29 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dogoworbalance_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogoworaccrual',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.accrualcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='dogoworaccrual',
            name='dogowor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='core.userdogowor', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='dogoworbalance',
            name='dogowor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='core.userdogowor', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='dogoworpayment',
            name='dogowor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.userdogowor', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='dogoworpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogowor_payments', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='useractionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='DogoworLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=500, verbose_name='Логин')),
                ('dogowor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login', to='core.userdogowor', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Логин',
                'verbose_name_plural': 'Логины',
            },
        ),
    ]
