# Generated by Django 5.2.7 on 2025-10-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dogoworaccrual_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdogowor',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Описание действия'),
        ),
    ]
