# Generated by Django 5.2.7 on 2025-11-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userdogowor_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdogowor',
            name='login',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Логин'),
        ),
        migrations.DeleteModel(
            name='DogoworLogin',
        ),
    ]
