# Generated by Django 5.2.7 on 2025-11-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userdogowor_login_delete_dogoworlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='is_active',
        ),
    ]
