# Generated by Django 5.2.7 on 2025-11-05 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_usertable_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=1024, verbose_name='Услуга')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterField(
            model_name='usertable',
            name='is_enterprises',
            field=models.BooleanField(default=False, verbose_name='Предприятия'),
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Дата подключения')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата отключения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('actual_price', models.FloatField(verbose_name='Фактическая цена на момент подключения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date_connected', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время подключения')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_services', to=settings.AUTH_USER_MODEL, verbose_name='Кто подключил')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_services', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usertable')),
            ],
            options={
                'verbose_name': 'Услуга абонента',
                'verbose_name_plural': 'Услуги абонентов',
                'ordering': ['-date_connected'],
                'unique_together': {('user', 'service')},
            },
        ),
        migrations.AddField(
            model_name='usertable',
            name='services',
            field=models.ManyToManyField(blank=True, through='core.UserService', through_fields=('user', 'service'), to='core.service', verbose_name='Услуги'),
        ),
    ]
