# Generated by Django 5.2.7 on 2025-11-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_service_alter_usertable_is_enterprises_userservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='abonplata',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Абонплата'),
        ),
    ]
