# Generated by Django 5.2.7 on 2025-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogoworaccrual',
            name='category',
            field=models.CharField(blank=True, choices=[('abonplata', 'Абонплата'), ('slr', 'SLR'), ('kod', 'KOD'), ('zakaz', 'ZAKAZ'), ('uslugi', 'Услуги'), ('internet', 'Интернет'), ('belet', 'Belet'), ('kabel', 'Кабельное'), ('alem', 'Alem')], max_length=20, null=True, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='AccrualCategory',
        ),
    ]
