# Generated by Django 5.2.7 on 2025-11-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_dogoworaccrual_category_delete_accrualcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogoworaccrual',
            name='month',
        ),
        migrations.RemoveField(
            model_name='dogoworaccrual',
            name='year',
        ),
        migrations.AddField(
            model_name='dogoworaccrual',
            name='period',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Период начисления'),
        ),
    ]
