# Generated by Django 5.2.7 on 2025-11-14 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0019_dogoworaccrual_user_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('action', models.CharField(max_length=255, verbose_name='Тип действия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Данные до изменения')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Данные после изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=20, verbose_name='Уровень')),
                ('status', models.CharField(blank=True, default='success', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время действия')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Модель объекта')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто сделал')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_action_created_93ebdb_idx'), models.Index(fields=['content_type', 'object_id'], name='core_action_content_3ec7a4_idx'), models.Index(fields=['user'], name='core_action_user_id_209dab_idx')],
            },
        ),
    ]
