# Generated by Django 5.2.7 on 2025-11-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_actionhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionHistory',
        ),
    ]
