# Generated by Django 5.2.7 on 2025-11-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_abonenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonenthistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История изменений', 'verbose_name_plural': 'Истории изменений'},
        ),
    ]
