# Generated by Django 5.2.7 on 2025-11-14 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_abonenthistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonenthistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История изменений Абонента', 'verbose_name_plural': 'Истории изменений Абонентов'},
        ),
        migrations.AlterField(
            model_name='abonenthistory',
            name='abonent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.usertable', verbose_name='Абонент'),
        ),
        migrations.AlterField(
            model_name='abonenthistory',
            name='action',
            field=models.CharField(choices=[('create', 'Создать'), ('update', 'Изменить'), ('delete', 'Удалить')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='abonenthistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено'),
        ),
        migrations.AlterField(
            model_name='abonenthistory',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='abonenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='abonenthistory',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Измененное поле'),
        ),
        migrations.AlterField(
            model_name='abonenthistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='abonenthistory',
            name='new_value',
            field=models.TextField(blank=True, null=True, verbose_name='Новое значение'),
        ),
        migrations.AlterField(
            model_name='abonenthistory',
            name='old_value',
            field=models.TextField(blank=True, null=True, verbose_name='Старое значение'),
        ),
    ]
