# Generated by Django 5.2.7 on 2025-11-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_abonenthistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonenthistory',
            name='dogowor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_dogowor', to='core.userdogowor', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='abonenthistory',
            name='abonent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_abonent', to='core.usertable', verbose_name='Абонент'),
        ),
    ]
