# Generated by Django 5.2.7 on 2025-11-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_abonenthistory_dogowor_alter_abonenthistory_abonent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonenthistory',
            name='action',
            field=models.CharField(choices=[('installed', 'installed'), ('updated', 'updated'), ('deactivated', 'deactivated'), ('installed new IPTV dogowor', 'installed new IPTV dogowor')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='date_connected',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время подключения'),
        ),
    ]
